### ISSUE TITLE
Recode error columns

### ISSUE THREAD

**Issue by LiamDBailey** [SPI-Birds/pipelines#105]
Currently, BroodSizeError is treated the same as other errors (i.e. +- around the best estimate); however, in BroodSize there is an absolute number known/observed a number unobserved and a number dead. Should the best estimate (i.e. BroodSize column) be the number observed or the (observed + unobserved/2)?

**Comment by LiamDBailey** [comment]
More broadly, we have an issue with how we code error in our data. In some cases error is expected to be symmetrical, such that we can provide a best estimate (mean) and error (+-); however, in other cases error may be asymmetrical. For example, in the original estimate of brood size our best estimate is the number of observed checks. We know there may be some positive error (i.e. it could be larger) but we know there is no negative error (i.e. it could never be smaller).

We can overcome this issue by providing three, rather than two, columns. One column will be the observed/recorded value, one will be the minimum possible value, the third will be the maximum possible value. In the laydate example, observed, min, and max will all be unique. In the brood size example, min and observed are identical.

**Comment by LiamDBailey** [comment]
@ChloeRN and @StefanVriend. Implementing this now for the AMM pipeline. One issue we never discussed was how to deal with cases where error is open ended (e.g. when clutch size is recorded as '7+'). I can see two solutions:

1. **` ClutchSize_observed = 7; ClutchSize_min = 7; ClutchSize_max = Inf`**
2. **` ClutchSize_observed = 7; ClutchSize_min = 7; ClutchSize_max = maximum clutch size from Stefan's checks`**

Option 1 is most accurate but less informative. We do not know the maximum value, all we know is that it would be larger than 7. But this ignores our biological knowledge. We don't know the exact maximum value of the clutch, but we are very confident it's not e.g. 100! 😆 

Option 2 requires us to make an assumption about the maximum possible clutch and raises all the same issues as those Stefan has encountered with his checks. I think this was fine in the checks because it's happening 'behind the scenes' and is just used to make a *suggestion* to the user/data owner, but in this case we'll be placing our assumed maximum value directly in the data.

I'm erring towards option 1, because I'm a bit wary about putting our assumed max/min values directly into the data. Also, if we wanted to make those max/min value dynamic (i.e. updating each time we get new data) this will mean that the data will change often which is not great for reproducibility. Also, most people will just use the observed value anyway!!

Thoughts?

**Comment by LiamDBailey** [comment]
Though this becomes more complex when we have an open ended minimum (e.g. '7-'). I would read this as a 'clutch with at most 7 eggs'. So I think we would need to have:

**` ClutchSize_observed = 7; ClutchSize_min = 1; ClutchSize_max = 7`**

If there was *no* clutch it would be '0', not '7-', so we know for sure that the minimum would be 1. Is there anything I'm missing there?

**Comment by ChloeRN** [comment]
@LiamDBailey. I agree with you that Option 2 is definitely not what we want to do here. While Option 1 is definitely preferable, I considered setting ClutchSize_max = NA in these cases instead. However, I think that may generate some confusion (i.e. difference between having ClutchSize_min and ClutchSize_max = NA when no data on error is available versus only ClutchSize_max = NA when minimum number has been observed). So, as much as "Inf" is biological bullshit, it functions well as flag for "use your own judgement" for the data user. So, I'd say let's go with option 1.

I agree, "7-" would indicate minimum 1, maximum 7.

**Comment by LiamDBailey** [comment]
Will be good to get feedback from the steering committee on this.

**Comment by LiamDBailey** [comment]
Some more thoughts on this:

**Date columns (LayDate/HatchDate/FledgeDate)**
- We can have open ended minimum date (e.g. nest first found with fledglings so all we know is laying date was earlier than the first observation). In this case `XXXDate_minimum = -Inf`.
- We cannot have an open ended maximum date. When a nest has been found the maximum could at most be the same as the observation date (i.e. nest found on the day of laying/hatching/fledging). Therefore, `XXXDate_maximum` can never be Inf.

**Integer columns (ClutchSize/BroodSize/NumberFledged)**
- All these columns should have the same behaviour as discussed for clutch size above. `XXX_minimum` can never be negative (and can not be <1 if a non-zero best estimate is provided). `XXX_maximum` can reach Inf if error is open ended.
- _**Except**_ that `BroodSize_minimum` must be >= `ClutchSize_minimum` and `NumberFledge_minimum` must be >= `BroodSize_minimum`.

**Comment by StefanVriend** [comment]
Considering your options, @LiamDBailey, and reading @ChloeRN's suggestions, I think option 1 has my preference. We should be very clear in the standard protocol wat `Inf` means in those cases.

Regarding:
> **BroodSize/NumberFledged**
>- If size of previous stage is known, BroodSize_maximum must be <= ClutchSize_maximum and NumberFledged_maximum must be <= BroodSize_maximum.

Do you mean here that you want to ensure this when creating the pipeline or is this more something we will check in the quality check? We can easily extend the current check (flag records where BroodSize > ClutchSize & NumberFledged > BroodSize) to include Max columns.

**Comment by LiamDBailey** [comment]
@StefanVriend I think the BroodSize/NumberFledged restrictions are something we will include in the pipeline rather than needing to verify in the quality check.

RE: Different meanings of '7+'. I think you're right they could mean different things, so it would probably be worth checking (I already had to recontact people from the Ammersee population to verify what their error column means), but this should be achieved during the discussion we already have with the data owners so it shouldn't be too much extra work.

**Comment by LiamDBailey** [comment]
Included in standard protocol v1.1
