### ISSUE TITLE
Create unique CaptureID column

### ISSUE THREAD

**Issue by LiamDBailey** [SPI-Birds/pipelines#108]
Currently, unique captures can be identified using a combination of IndvID and date; however, for our quality check we want a single unique identifier so we can easily identify/whitelist troublesome capture records.

CaptureID should be a concatenation in the form 'IndvID_CaptureNr', where capture number ranges from 1 (first capture) - Inf.

This also needs to be implemented retrospectively for all other pipelines.

**Comment by StefanVriend** [comment]
Do you think it will be alright to already build the whitelist functionality around this, or shall I wait until this has been implemented in all pipelines?

**Comment by LiamDBailey** [comment]
Maybe for now just add a column during the quality check called CaptureID which is just a sequence of numbers. Once we've implemented CaptureID properly in the pipelines we can remove this column.

**Comment by LiamDBailey** [comment]
Included in standard protocol v1.1
