### ISSUE TITLE
Ignore column checks when making the warning/error columns

### ISSUE THREAD

**Issue by LiamDBailey** [SPI-Birds/pipelines#109]
The quality check produces the output report but also adds a 'warning' and 'error' column to help users identify troublesome rows. We need to make sure that the 'warning' column is ignoring checks of missing columns because this is often expected behaviour.

**Comment by LiamDBailey** [comment]
@StefanVriend I think we may have already dealt with this because the error/warning columns are row specific not column specific. So we may already be ignoring the full column checks.

**Comment by StefanVriend** [comment]
I just checked the code (lines 182-204 of brood_check.R for instance) and I can confirm that the format checks are not included there!
