### ISSUE TITLE
Add ExperimentID in Capture_data

### ISSUE THREAD

**Issue by LiamDBailey** [SPI-Birds/pipelines#113]
e.g. if an adult is caught and taken to a lab this could affect survival. We need to record when this happened.

**Comment by LiamDBailey** [comment]
We would probably also need to deal with death information (which is distinct from experimentation). So we would have:

- CaptureExperiment (almost always SURVIVAL, but could be PHENOLOGY or something similar)
- CaptureStatus (Dead or Alive)
- ReleaseStatus (Dead or Alive)

**Comment by LiamDBailey** [comment]
@ChloeRN. For these columns, I think it makes more sense to have CaptureAlive and ReleaseAlive which can be TRUE/FALSE. This prevents possible bugs due to typos (e.g. 'dead' instead of 'Dead') and it is a more efficient way to store data (just 0/1).

**Comment by ChloeRN** [comment]
@LiamDBailey. This makes sense, great suggestion! Let's do it this way.

**Comment by ChloeRN** [comment]
This is now implemented in the newly finished PFN (and AMM?) pipelines, and will be implemented in all pipelines to be built from now on. 
Do we close this once we have implemented the 1.1. updates in ALL "historical" pipelines?

**Comment by LiamDBailey** [comment]
@ChloeRN yes, I think we should wait until it's included in ALL pipelines before we mark this as closed. Otherwise we might forget to update the old ones 😅

**Comment by LiamDBailey** [comment]
Included in standard protocol v1.1. Contrary to my comment above, I'm going to close this and we will create a new issue to update old pipelines to the standard protocol.
