### ISSUE TITLE
Change reference value checks: compare with data rather than arbitrary values

### ISSUE THREAD

**Issue by StefanVriend** [SPI-Birds/pipelines#117]
Reference value checks (in Brood_data and Capture_data) currently use reference values that are arbitrarily picked (but semi-informed by data). We think, however, that it is better to compare values with data. If datasets are large enough (**NB:** we have to determine what that means), we will compare reference values with the data they originate from. If datasets are small, we will compare with a back-up, for instance NIOO data.

**Comment by StefanVriend** [comment]
During SPI-Birds week we've discussed setting the upper boundary of legitimate values to the 99th percentile ("warning max"). 
The upper boundary of unlikely values will be 4 times the 99th percentile ("error max"); I currently see no way around setting an arbitrary value for this.

**Comment by LiamDBailey** [comment]
We could easily adjust the error boundary if we notice it's too conservative/not conservative enough when using for populations
