### ISSUE TITLE
Fix Python library errors on Mac (HAR & KEV pipelines)

### ISSUE THREAD

**Issue by ChloeRN** [SPI-Birds/pipelines#134]
Pipelines for HAR and KEV use Python code to extract data from the "paradox databases". This does not currently work on Mac, as the "pipxlib" library cannot be found. Need to fix this, or come up with a work-around.

**Comment by ChloeRN** [comment]
I have now gotten around to fixing this. 
This involved two steps: the correct set-up of the python environment for r-reticulate on MacOS (notes in the next comments), and a change in pathname specification within the extract_paradox_db() function (commit within #133 ).

**Comment by ChloeRN** [comment]
Notes on how to set up python environment for r-reticulate on MacOS, including necessary libraries: 

1. Install Anaconda 3.8

2. Check your default python version by opening terminal and typing: python3 --version 
   (This should return Python 3.8.X)

3. Check that pip is available by typing: pip3 --version

4. Update pip by typing: python3 -m pip install --user --upgrade pip
   (You have to use the --user argument as permission may be denied otherwise)

5. Open RStudio and load the reticulate package: library(reticulate)

6. Check which version of python reticulate is linked to: py_config()
   (Required python libraries need to be installed into this virtual environment)

7. Install pandas library from within R: py_install("pandas")

8. Install pypxlib library from within R: py_install("pypxlib", pip = TRUE)
   (Since this is an external library hosted on GitHub, you need to specify installation via pip)

9. Check that both libraries are now available:
   py_module_available("pandas")
   py_module_available("pypxlib")
   (Both commands should return TRUE)

With this setup, python should be good to go for extracting paradox databases. 
(Note that when I installed Anaconda, the r-reticulate environment was already present. If that is not the case, one may have to first generate the environment and link it to RStudio).

**Comment by zuzulaz** [comment]
@ChloeRN I followed your notes to set up of the python, worked ok. I will let you know how the function works.

**Comment by LiamDBailey** [comment]
In the future it may be worth us creating a Python virtual environment with all the loaded libraries that can stored on the repo. Leaving this comment here for a future reminder!

**Comment by LiamDBailey** [comment]
@ChloeRN Could you add this information to the README for the repo?

**Comment by ChloeRN** [comment]
@LiamDBailey will do!
