### ISSUE TITLE
Check that parents are not of the same sex

### ISSUE THREAD

**Issue by StefanVriend** [SPI-Birds/pipelines#142]
@zuzulaz found some instances in the PEW pipeline where broods have parents of the same sex. We do check sex uncertainty across captures of the same individual, so there is information when, for instance, one parent has one sex and the other parent a conflicted sex ("C"). However, we do not compare the sexes of the parents.

I think there are two ways in which we can highlight these issues in the quality check report. 

1. Either we simply compare the sex of the individuals under FemaleID and MaleID and print something like "Record on Row X, BroodID Y has parents of the same sex ("M")". 
2. Or we write the check more general and test for records where the individual in FemaleID is not female and the individual in MaleID is not male (in this way we can also catch the (perhaps unlikely) cases where mother and father are swapped). The line in the report would then be something like: "Record on Row X, BroodID Y has an individual in [FemaleID/MaleID] that is not a [female/male]."

Any thoughts? @LiamDBailey @ChloeRN @zuzulaz

**Comment by ChloeRN** [comment]
Hi @StefanVriend! I think I your second solution seems more useful generally. What is important I think though is that the checks will only flag an entry for "misplaced" FemaleIDs/MaleIDs that are not already associated with "conflicting sex" in individual data.  If sex is conflicted anyways, I think we should only flag that in the Individual data (if data  owners then fix the source of that, it will be fixed everywhere). 
So the report coming out of your query should be more something like: 
"Record on Row X, BroodID Y has an individual in [FemaleID/MaleID] that is of the opposite sex"

or, perhaps it would be even more useful to have "specific" reports, i.e.
"Record on Row X, BroodID Y lists a male individual under FemaleID."
"Record on Row X, BroodID Y lists a female individual under MaleID."

**Comment by StefanVriend** [comment]
Yes, I totally agree. This check will only target non-conflicted sex individuals.
I like your second suggestion as well. The specific reports contain the most useful information for both data owner and user.
