### ISSUE TITLE
All NAs for ExperimentIDs in PARMAJ capture records

### ISSUE THREAD

**Issue by cwtyson** [SPI-Birds/pipelines#174]
In the full standard data, all ExperimentID values for PARMAJ captures are NA. Other species have values though.

**Comment by cwtyson** [comment]
@LiamDBailey I think it is a different issue, but it might be related. The problem here is that there are no ExperimentIDs for PARMAJ, which seems suspicious. For #175, the ExperimentID column is missing from the capture table returned by format_AMM.

**Comment by LiamDBailey** [comment]
@cwtyson this is then the same issue right? If the ExperimentID column is missing in `format_AMM()` then it will be filled with NAs when we use `dplyr::bind_rows()` to combine different pipeline outputs. Can you give me a reprex if I'm not understanding.

**Comment by cwtyson** [comment]
True, but I would think other populations would have PARMAJ capture records associated with experiments. There might not be any though if AMM is the only population with many PARMAJ records that is formatted to the protocol version 1.1 since ExperimentID wasn't part of the capture table in version 1.0. In that case, this issue would be fixed.

**Comment by LiamDBailey** [comment]
Yea, it's a bit hard to say without knowing all the experimental history of each population 😅. For now #178 should add ExperimentID for AMM, and we should just keep an eye on this in the future.

**Comment by cwtyson** [comment]
Sounds good
