### ISSUE TITLE
Update all internal data in the pipelines package

### ISSUE THREAD

**Issue by StefanVriend** [SPI-Birds/pipelines#25]
For instance, the files and variables of pop_names.rda and Species_codes.rda are inconsistently named.

**Comment by LiamDBailey** [comment]
We need to a) ensure naming convention is consistent and b) ensure that any data that will require editing in the future is in a format that can be tracked by GitHub.

**Comment by LiamDBailey** [comment]
I think that storing a .csv file would be most appropriate to allow for track changes and easy editing.

**Comment by LiamDBailey** [comment]
@StefanVriend assigned to you as this is also relevant for your quality check data.

**Comment by StefanVriend** [comment]
I propose following.

I will change the following .rda files into .csv:

- species_codes
- pop_codes (formerly pop_names)
- pop_species_combos
- checkID_variable_combos (formerly checkID_var)

The following .rda files are created using a script in /R, so those are already trackable by GitHub:

- approved_list
- dummy_data

The following .rda files will likely change under quality check update, so they will be updated later:

- brood_ref_values
- capture_ref_values
- chick_mass_cutoffs

The following .rda files have only been used for a single purpose. **What shall I do with them?**

- GT_dist_gg
- bird_png_data
