### ISSUE TITLE
Check for individuals classified as multiple species in capture data

### ISSUE THREAD

**Issue by LiamDBailey** [SPI-Birds/pipelines#30]
Firstly, we need to create a new value in the species column that highlights individuals who have been classified as multiple species. This needs to be done inside the pipeline.

Next, we need the quality check to identify all individuals with conflicting species listings and return some information on which individual it was and which species it was classified as (using information in the capture data table).

**Comment by StefanVriend** [comment]
This check has been made in Individual_data and flags records that have Species. marked as "CONFLICTED".
