### ISSUE TITLE
Create a wrapper function to subset standard data

### ISSUE THREAD

**Issue by LiamDBailey** [SPI-Birds/pipelines#77]
Instead of using `run_pipeline` with different values of PopID every time a request is sent, instead we should use `run_pipeline` once to create a full 'standard dataset' and then create a wrapper function to subset this standard data into data requested by users. This will be a more efficient way of approaching the problem.

**Comment by LiamDBailey** [comment]
@ChloeRN we've already created the function `subset_datarqst` that should cover most of this, but it would be good to double check if this covers everything we need *and* to create some tests for it in the package.

**Comment by ChloeRN** [comment]
@LiamDBailey that seems sensible. 
This also reminds me of what we talked about a little while ago regarding subsetting and conflicting species: when subsetting all outputs by Species, individuals with conflicting species will be contained in Capture Data, but not Individual Data. If I recall correctly, we agreed it would make sense to subset Individual Data not by Species, but instead by all IndvID's contained in the subsetted Capture Data. Should we incorporate this into the subset function?

**Comment by LiamDBailey** [comment]
Yea, that's a good point. Perhaps you could include an argument like `include.conflicted` that can be turned on and off? That way we can choose whether to include these individuals.

**Comment by ChloeRN** [comment]
Yes, that makes sense. 
However, if include.conflicted = F, should we then remove any captures of conflicted species individuals from Capture Data?
(Ideally, I think we would avoid the output containing captures of individuals that are not included in Individual Data).

**Comment by LiamDBailey** [comment]
Yes, I think that's a good idea. Basically the user can decide whether they want the conflicted individuals or not and if not we remove them from everywhere.

**Comment by ChloeRN** [comment]
Now addressed in pull request #133.
