### ISSUE TITLE
Replace choose.dir() by OS-independent alternative

### ISSUE THREAD

**Issue by StefanVriend** [SPI-Birds/pipelines#79]
```choose.dir()``` is a Windows-only function. A possible work-around:

```
choose_directory = function(caption = 'Select data directory') {
  if (exists('utils::choose.dir')) {
    choose.dir(caption = caption) 
  } else {
    tk_choose.dir(caption = caption)
  }
}
```

**Comment by LiamDBailey** [comment]
Closed with commit ae44492e89044709926df266b27c1d65b8a5b0d1.

We now use rstuidoapi::selectDirectory() by default. This is OS agnostic as long as the user is running RStudio.
