### ISSUE TITLE
Create whitelist - Make checks column specific

### ISSUE THREAD

**Issue by LiamDBailey** [SPI-Birds/pipelines#80]
To create a whitelist, we have to know that a particular check (e.g. check B1) is only relevant for a particular column/set of columns (e.g. clutch size or lay date < hatch date). That way we can create a whitelist that can include information about whether a particular value in a particular column is verified, even if other values in the same row are not.

**Comment by StefanVriend** [comment]
For instance, B6: "Check brood variable values against reference values" checks different variables in BroodData match with reference values. We have to separate these checks into B6a, B6b, etc., where each variable (e.g. clutch size, brood size) are checked separately.
